### ISSUE TITLE
Webpack bundle: code splitting and dynamic import with server side rendering

### ISSUE THREAD

**Issue by jaybe78** [ConsenSys/SHR#39]
Loading only the minimal amount of code when the app initializes and additional code is loaded on demand. This can help tremendously with performance by allowing for a reduced initial bundle size.

**Comment by whitmoyer** [comment]
@jaybe78 Did you mean to have this under Front end?

**Comment by john-packel** [comment]
Let's discuss these column descriptions in Friday meeting, but I was thinking of this Design column as distinct from FE tasks, and we may want to start a new board when we start developing (i.e., translating designs to FE, etc.).

**Comment by jaybe78** [comment]
Used webpack to split vendors and main bundles
Implemented isomorphic component to load component on demand
